<!-- <script>
    document.writ('Hello')/// runtime error///
    // syntax is correct but method is not existed
    document.write('hello')//success because provided correct method
</script> -->

<!-- <script>
    // SyntaxError will occurre at whole page
    // runtime error will occure where the errors is coming
    /// it won't reflect to any other programs
    document.write('hello')//success
    document.writ(' hello hi')//errors
</script> -->
    <!-- <script>
        // if any errors is coming from first line then the whole program wii not execute
        document.writ('hello')//success
        document.write(' hello hi')//errors
    </script> -->

<!-- to solve the runtime error we have try catch finally statement -->

<!-- it allows you to test a block of code for errors -->
<!-- the try block contains the code to be run -->
<!-- catch block contains the code to be execute -->
<script>
    try{
        aler('hi')
    }catch{
        alert('catch')
    }
</script>
